### ISSUE TITLE
MATLAB Version

### ISSUE THREAD

**Issue by SeekerCode** [Ayatans/Machine-Learning-homework#1]
请问一下，笔者所写的课程作业所用的matlab是哪个发行版本嘛？

**Comment by Ayatans** [comment]
> 请问一下，笔者所写的课程作业所用的matlab是哪个发行版本嘛？

我记得是当时的最新版，2019b或者2020a吧

**Comment by SeekerCode** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢啦，我现在用的是2018b版本的，感觉差别应该不大。
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1280395843
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 12/29/2021 ***@***.***> wrote： 






请问一下，笔者所写的课程作业所用的matlab是哪个发行版本嘛？



我记得是当时的最新版，2019b或者2020a吧



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>
